//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_EF.AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int idTelefono { get; set; }
        public int idPersona { get; set; }
        public string Telefono1 { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
